package pubsub

import (
	"encoding/json"
	"fmt"
	"log"

	amqp "github.com/rabbitmq/amqp091-go"
)

type AckType int

const (
	Ack AckType = iota
	NackRequeue
	NackDiscard
)

func SubscribeJSON[T any](
	conn *amqp.Connection,
	queueName string,
	queueType SimpleQueueType,
	exchange,
	key string,
	handler func(T) AckType,
) error {
	channel, _, err := DeclareAndBindQueue(conn, queueName, queueType, exchange, key)
	if err != nil {
		return fmt.Errorf("failed to declare and bind queue: %w", err)
	}

	const (
		autoGeneratedConsumerName = ""
		disableAutoAck            = false
		nonExclusive              = false
		local                     = false
		wait                      = false
	)
	deliver, err := channel.Consume(
		queueName,
		autoGeneratedConsumerName,
		disableAutoAck,
		nonExclusive,
		local,
		wait,
		nil,
	)
	if err != nil {
		return fmt.Errorf("failed to start delivered messages consumption: %w", err)
	}

	go func() {
		for msg := range deliver {
			var val T
			if err := json.Unmarshal(msg.Body, &val); err != nil {
				log.Printf("failed to unmarshal message body: %v", err)
			}

			const (
				single  = false
				requeue = true
				discard = false
			)
			switch handler(val) {
			case Ack:
				msg.Ack(single)
			case NackRequeue:
				msg.Nack(single, requeue)
			case NackDiscard:
				msg.Nack(single, discard)
			}
		}
	}()

	return nil
}
